apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentiment-analysis-dev
  name: sentiment-analysis-dev
  namespace: models
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 9999
    protocol: TCP
  selector:
    app: sentiment-analysis-dev
  sessionAffinity: None
  type: LoadBalancer
